version: 2.1

executors:
  ci:
    docker:
      - image: landtech/ci-base

jobs:
  test:
    executor: ci
    steps:
      - checkout
      - run:
          command: |
            aws configure set profile.default.aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set profile.default.aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set profile.default.region "eu-west-1"

            # set up dependencies
            aws configure set profile.sandbox.region "eu-west-1"
            mkdir -p $HOME/.landtech
            credstash get aws/accounts.json > $HOME/.landtech/accounts.json

            make test

workflows:
  schedule:
    jobs:
      - test:
          context: AWS_STAGING
