version: 2.1

executors:
  default:
    docker:
      - image: docker:stable

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run: |
          bats assets

workflows:
  commit:
    jobs:
      - test:
          context: AWS_STAGING
