version: 2.1

executors:
  ci:
    docker:
      - image: landtech/ci-base

jobs:
  test:
    executor: ci
    steps:
      - checkout
      - run:
          command: |
            aws configure set profile.sandbox.aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set profile.sandbox.aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"

            # test dependencies
            mkdir -p .landtech
            credstash get aws/accounts.json > .landtech/accounts.json

            make test

workflows:
  schedule:
    jobs:
      - test:
          context: AWS_STAGING
