#!/usr/bin/env bash
set -e
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"

title "GoPass"

# dependencies
brew install gopass &>/dev/null

echo_install "configuring gopass"
gopass config exportkeys true >/dev/null
print_in_green "${bold}✓ done!${normal}\n"

echo_install "syncing gopass"
gopass sync >/dev/null
print_in_green "${bold}✓ done!${normal}\n"
