#!/usr/bin/env bash
source "$(cd "$(dirname "$0")" && pwd)/../pretty-print"

node_major="14"
node_ver="v$node_major.x"

modules=(
	eslint
	prettier
)

title "Node"

if ! command -v fnm &>/dev/null; then
	echo_install "Installing FNM…"
	brew install Schniz/tap/fnm &>/dev/null
	print_in_green "${bold}✓ installed!${normal}\n"
else
	print_success_muted "fnm"
fi

eval "$(fnm env)"

if [ "$FORCE" = true ] || ! fnm current | grep -q "v$node_major."; then
	echo_install "Installing node v$node_major"
	fnm install $node_ver &>/dev/null
	fnm default $node_ver
	print_in_green "${bold}✓ installed!${normal}\n"
else
	print_success_muted "node v$node_major"
fi

fnm use $node_major >/dev/null

for module in "${modules[@]}"; do
	if ! npm list -g "$module" >/dev/null; then
		echo_install "Installing $module"
		npm install "$module" -g --silent >/dev/null
		print_in_green "${bold}✓ installed!${normal}\n"
	else
		print_success_muted "$module"
		npm update "$module" -g --silent >/dev/null
	fi
done
